apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-to-github
  namespace: handson-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-to-github
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-to-github
    spec:
      containers:
        - image: quay.io/pfnet-alertmanager-to-github/alertmanager-to-github:v0.0.1
          name: main
          ports:
            - containerPort: 8080
          env:
            - name: ATG_LABELS
              value: "alerts"
            - name: ATG_LISTEN
              value: ":8080"
          envFrom:
            - secretRef:
                name: env-secrets # env secret has ATG_GITHUB_TOKEN
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 1m
              memory: 10Mi
