apiVersion: v1
kind: Service
metadata:
  name: alertmanager-to-github
  namespace: handson-demo
spec:
  selector:
    app.kubernetes.io/name: alertmanager-to-github
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
