---
apiVersion: v1
kind: Service
metadata:
  name: viewmap-svc
  labels:
    app: viewmap
spec:
  ports:
    - name: "80"
      port: 8080
      targetPort: 80
    - name: nginx-exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
  selector:
    app: viewmap
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app
spec:
  ports:
    - name: app-port
      port: 8080
      targetPort: 8080
  selector:
    app: app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  ports:
    - name: database-port
      port: 5432
      targetPort: 5432
  selector:
    app: database
status:
  loadBalancer: {}
