{
 "title": "ハンズオン用ダッシュボード",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "住所コードAPIのSLO指標",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(m__address_postalcode__param__GET_seconds_bucket{namespace=\"handson-demo\"}[30s]))) ",
     "legendFormat": "95%SLOレベル"
    }
   ]
  },
  {
   "title": "住所コードAPIサービスの1秒あたりのリクエスト数",
   "type": "graph",
   "description": "住所コードAPIサービスの1秒あたりのリクエスト数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(m__address_postalcode__param__GET_seconds_count[30s]))",
     "legendFormat": "サービス全体の1秒間あたりのリクエスト数"
    }
   ]
  },
  {
   "title": "住所コードAPIのDB処理",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(getAddressNameNoCache_seconds_sum[10s])/rate(getAddressNameNoCache_seconds_count[10s])",
     "legendFormat": "ポッド名:  {{pod}} メソッド名: {{method}}"
    },
    {
     "expr": "rate(getAddressName_seconds_sum[10s])/rate(getAddressName_seconds_count[10s])",
     "legendFormat": "ポッド名:  {{pod}} メソッド名: {{method}}"
    }
   ]
  },
  {
   "title": "住所コードAPIの文字列変換処理",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(convertAddressName_seconds_sum[10s])/rate(convertAddressName_seconds_count[10s])",
     "legendFormat": "ポッド名:  {{pod}} メソッド名: {{method}}"
    }
   ]
  }
 ]
}